section .text

global hash_mix

sub_407C40:		; CODE XREF: sub_407809+42Ap


		push	ebp
		lea	ebp, [esp-78h]
		sub	esp, 9Ch
		mov	ecx, [eax+24h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [eax+28h]
		mov	edx, [eax+4]
		mov	[ebp+68h], ecx
		mov	ecx, [eax+2Ch]
		mov	[ebp+64h], ecx
		mov	ecx, [eax+30h]
		mov	[ebp+70h], ecx
		mov	ecx, [eax+34h]
		mov	[ebp+74h], ecx
		mov	ecx, [eax+38h]
		mov	[ebp+60h], ecx
		mov	ecx, [eax+3Ch]
		mov	[ebp+54h], ecx
		mov	ecx, [eax+40h]
		mov	[ebp+5Ch], ecx
		mov	ecx, [eax+44h]
		add	ecx, edx
		push	ebx
		push	esi
		mov	esi, [eax+8]
		push	edi
		mov	edi, [eax+0Ch]
		mov	[ebp+18h], ecx
		mov	ecx, [eax+48h]
		add	ecx, esi
		mov	[ebp+24h], ecx
		mov	ecx, [eax+4Ch]
		add	ecx, edi
		mov	edi, [eax+60h]
		add	edi, [eax+20h]
		mov	esi, [eax+54h]
		mov	[ebp+40h], edi
		mov	edi, [eax+64h]
		add	edi, [ebp+6Ch]
		add	esi, [eax+14h]
		mov	[ebp+20h], edi
		mov	edi, [eax+68h]
		add	edi, [ebp+68h]
		mov	ebx, [eax+10h]
		mov	[ebp-0Ch], edi
		mov	edi, [eax+6Ch]
		add	edi, [ebp+64h]
		mov	edx, [eax+50h]
		mov	[ebp+38h], edi
		mov	edi, [eax+70h]
		add	edi, [ebp+70h]
		mov	[ebp+50h], esi
		mov	esi, [eax+58h]
		add	esi, [eax+18h]
		mov	[ebp+14h], edi
		mov	edi, [eax+74h]
		add	edi, [ebp+74h]
		mov	[ebp+48h], esi
		mov	esi, [eax+5Ch]
		add	esi, [eax+1Ch]
		mov	[ebp+4Ch], edi
		mov	edi, [eax+78h]
		add	edi, [ebp+60h]
		add	edx, ebx
		mov	[ebp+28h], edi
		mov	edi, [eax+7Ch]
		add	edi, [ebp+54h]
		mov	[ebp+3Ch], edi
		mov	edi, [eax+80h]
		add	edi, [ebp+5Ch]
		mov	[ebp+44h], edi
		mov	edi, [eax+4]
		mov	[ebp+58h], edi
		mov	edi, [eax+8]
		mov	[ebp-10h], edi
		mov	edi, [eax+0Ch]
		mov	[ebp-20h], edi
		mov	edi, ebx
		mov	[ebp+2Ch], edi
		mov	edi, [eax+14h]
		mov	[ebp-14h], edi
		mov	edi, [eax+18h]
		mov	[ebp-1Ch], edi
		mov	edi, [eax+1Ch]
		mov	[ebp+30h], edi
		mov	edi, [eax+20h]
		mov	[ebp+34h], edi
		mov	edi, [ebp+6Ch]
		rol	edi, 7
		xor	edi, [ebp+18h]
		mov	[ebp+0], edi
		mov	edi, [ebp+68h]
		rol	edi, 7
		xor	edi, [ebp+24h]
		mov	[ebp-4], edi
		mov	edi, [ebp+64h]
		rol	edi, 7
		xor	edi, ecx
		mov	[ebp+10h], edi
		mov	edi, [ebp+70h]
		rol	edi, 7
		xor	edi, edx
		mov	[ebp+0Ch], edi
		mov	edi, [ebp+74h]
		rol	edi, 7
		xor	edi, [ebp+50h]
		mov	[ebp-24h], edi
		mov	edi, [ebp+60h]
		rol	edi, 7
		xor	edi, [ebp+48h]
		mov	[ebp+1Ch], edi
		mov	edi, [ebp+54h]
		rol	edi, 7
		xor	edi, esi
		mov	[ebp+8], edi
		mov	edi, [ebp+5Ch]
		rol	edi, 7
		xor	edi, [ebp+40h]
		mov	[ebp+4], edi
		mov	edi, [ebp+58h]
		rol	edi, 7
		xor	edi, [ebp+20h]
		mov	[ebp+6Ch], edi
		mov	edi, [ebp-10h]
		rol	edi, 7
		xor	edi, [ebp-0Ch]
		mov	[ebp+68h], edi
		mov	edi, [ebp-20h]
		rol	edi, 7
		xor	edi, [ebp+38h]
		mov	[ebp+64h], edi
		mov	edi, ebx
		mov	ebx, [ebp+18h]
		rol	edi, 7
		xor	edi, [ebp+14h]
		mov	[ebp+58h], ebx
		mov	ebx, [ebp+24h]
		mov	[ebp+70h], edi
		mov	edi, [ebp-14h]
		rol	edi, 7
		xor	edi, [ebp+4Ch]
		mov	[ebp-8], ebx
		mov	ebx, [ebp+50h]
		mov	[ebp+74h], edi
		mov	edi, [ebp-1Ch]
		rol	edi, 7
		xor	edi, [ebp+28h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+48h]
		mov	[ebp+60h], edi
		mov	edi, [ebp+30h]
		rol	edi, 7
		xor	edi, [ebp+3Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+20h]
		mov	[ebp-20h], ebx
		mov	ebx, [ebp-0Ch]
		mov	[ebp+54h], edi
		mov	edi, [ebp+34h]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+4Ch]
		rol	edi, 7
		xor	edi, [ebp+44h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+28h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+0]
		add	ecx, ebx
		mov	[ebp+18h], ecx
		mov	ecx, [ebp-4]
		add	edx, ecx
		mov	ecx, [ebp+58h]
		mov	ebx, [ebp+8]
		mov	[ebp+24h], edx
		mov	edx, [ebp+10h]
		add	ecx, edx
		mov	edx, [ebp+0Ch]
		mov	[ebp-10h], ecx
		mov	ecx, [ebp-8]
		add	ecx, edx
		mov	edx, [ebp+1Ch]
		mov	[ebp-8], ecx
		mov	ecx, [ebp-24h]
		add	esi, ecx
		mov	[ebp+50h], esi
		mov	esi, [ebp+40h]
		add	esi, edx
		mov	[ebp+48h], esi
		mov	esi, [ebp-18h]
		add	esi, ebx
		mov	ebx, [ebp+4]
		mov	[ebp+58h], esi
		mov	esi, [ebp+5Ch]
		add	esi, ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp+40h], esi
		mov	esi, [ebp+38h]
		add	esi, ebx
		mov	ebx, [ebp+68h]
		mov	[ebp+20h], esi
		mov	esi, [ebp+14h]
		add	esi, ebx
		mov	ebx, [ebp+64h]
		mov	[ebp-0Ch], esi
		mov	esi, [ebp-20h]
		add	esi, ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+38h], esi
		mov	esi, [ebp+2Ch]
		add	esi, ebx
		mov	ebx, [ebp+74h]
		mov	[ebp+14h], esi
		mov	esi, [ebp+3Ch]
		add	esi, ebx
		mov	ebx, [ebp+60h]
		mov	[ebp+4Ch], esi
		mov	esi, [ebp+44h]
		add	esi, ebx
		mov	ebx, [ebp+30h]
		mov	[ebp+28h], esi
		mov	esi, [ebp+54h]
		add	ebx, esi
		mov	[ebp+3Ch], ebx
		mov	ebx, [ebp+34h]
		add	ebx, edi
		mov	[ebp+44h], ebx
		mov	ebx, [ebp+0]
		mov	[ebp+1Ch], ebx
		mov	ebx, [ebp-4]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+10h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+0Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp-14h], ebx
		mov	ebx, [ebp+68h]
		mov	[ebp-1Ch], ebx
		mov	ebx, [ebp+64h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+18h]
		rol	ecx, 0Bh
		xor	ecx, ebx
		mov	[ebp+0], ecx
		mov	ecx, [ebp+8]
		rol	edx, 0Bh
		xor	edx, [ebp+24h]
		rol	ecx, 0Bh
		xor	ecx, [ebp-10h]
		mov	[ebp-4], edx
		mov	[ebp+10h], ecx
		mov	ecx, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp-8]
		mov	edx, [ebp-0Ch]
		mov	[ebp+0Ch], ecx
		mov	ecx, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+50h]
		mov	[ebp-24h], ecx
		mov	ecx, [ebp+2Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+48h]
		mov	[ebp+1Ch], ecx
		mov	ecx, [ebp-18h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+58h]
		mov	[ebp+8], ecx
		mov	ecx, [ebp+5Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+40h]
		mov	[ebp+4], ecx
		mov	ecx, [ebp+74h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+20h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [ebp+60h]
		rol	ecx, 0Bh
		xor	ecx, edx
		rol	esi, 0Bh
		xor	esi, [ebp+38h]
		rol	edi, 0Bh
		mov	[ebp+68h], ecx
		mov	ecx, [ebp-14h]
		mov	[ebp+64h], esi
		mov	esi, [ebp+14h]
		xor	edi, esi
		mov	[ebp+70h], edi
		mov	edi, [ebp+0]
		mov	[eax+4], edi
		mov	edi, [ebp-4]
		mov	[eax+8], edi
		mov	edi, [ebp+10h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+4Ch]
		mov	[eax+0Ch], edi
		mov	edi, [ebp+0Ch]
		mov	[ebp+74h], ecx
		mov	ecx, [ebp-1Ch]
		mov	[eax+10h], edi
		mov	edi, [ebp-24h]
		mov	[eax+14h], edi
		mov	edi, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+28h]
		mov	[eax+18h], edi
		mov	edi, [ebp+8]
		mov	[ebp+60h], ecx
		mov	ecx, [ebp+30h]
		mov	[eax+1Ch], edi
		mov	edi, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp+3Ch]
		mov	[eax+20h], edi
		mov	edi, [ebp+6Ch]
		mov	[eax+24h], edi
		mov	edi, [ebp+68h]
		mov	[ebp+54h], ecx
		mov	ecx, [ebp+34h]
		mov	[eax+28h], edi
		mov	edi, [ebp+64h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+44h]
		mov	[eax+2Ch], edi
		mov	edi, [ebp+70h]
		mov	[eax+40h], ecx
		mov	ecx, [ebp+24h]
		mov	[eax+44h], ecx
		mov	ecx, [ebp-8]
		mov	[eax+4Ch], ecx
		mov	ecx, [ebp-10h]
		mov	[eax+50h], ecx
		mov	ecx, [ebp+48h]
		mov	[eax+54h], ecx
		mov	ecx, [ebp+50h]
		mov	[eax+58h], ecx
		mov	ecx, [ebp+40h]
		mov	[eax+5Ch], ecx
		mov	ecx, [ebp+58h]
		mov	[eax+60h], ecx
		mov	ecx, [ebp+20h]
		mov	[eax+68h], ecx
		mov	ecx, [ebp+38h]
		mov	[eax+30h], edi
		mov	edi, [ebp+74h]
		mov	[eax+70h], ecx
		mov	ecx, [ebp+28h]
		mov	[eax+34h], edi
		mov	edi, [ebp+60h]
		mov	[eax+74h], ecx
		mov	ecx, [ebp+4Ch]
		mov	[eax+38h], edi
		mov	edi, [ebp+54h]
		mov	[eax+78h], ecx
		mov	ecx, [ebp+44h]
		mov	[eax+3Ch], edi
		pop	edi
		mov	[eax+6Ch], esi
		mov	[eax+7Ch], ecx
		mov	ecx, [ebp+3Ch]
		pop	esi
		mov	[eax+48h], ebx
		mov	[eax+64h], edx
		mov	[eax+80h], ecx
		pop	ebx
		add	ebp, 78h
		leave
		retn


sub_407809:		; CODE XREF: sub_4073D2+42Ap


		push	ebp
		lea	ebp, [esp-78h]
		sub	esp, 9Ch
		mov	ecx, [eax+24h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [eax+28h]
		mov	edx, [eax+4]
		mov	[ebp+68h], ecx
		mov	ecx, [eax+2Ch]
		mov	[ebp+64h], ecx
		mov	ecx, [eax+30h]
		mov	[ebp+70h], ecx
		mov	ecx, [eax+34h]
		mov	[ebp+74h], ecx
		mov	ecx, [eax+38h]
		mov	[ebp+60h], ecx
		mov	ecx, [eax+3Ch]
		mov	[ebp+54h], ecx
		mov	ecx, [eax+40h]
		mov	[ebp+5Ch], ecx
		mov	ecx, [eax+44h]
		add	ecx, edx
		push	ebx
		push	esi
		mov	esi, [eax+8]
		push	edi
		mov	edi, [eax+0Ch]
		mov	[ebp+18h], ecx
		mov	ecx, [eax+48h]
		add	ecx, esi
		mov	[ebp+24h], ecx
		mov	ecx, [eax+4Ch]
		add	ecx, edi
		mov	edi, [eax+60h]
		add	edi, [eax+20h]
		mov	esi, [eax+54h]
		mov	[ebp+40h], edi
		mov	edi, [eax+64h]
		add	edi, [ebp+6Ch]
		add	esi, [eax+14h]
		mov	[ebp+20h], edi
		mov	edi, [eax+68h]
		add	edi, [ebp+68h]
		mov	ebx, [eax+10h]
		mov	[ebp-0Ch], edi
		mov	edi, [eax+6Ch]
		add	edi, [ebp+64h]
		mov	edx, [eax+50h]
		mov	[ebp+38h], edi
		mov	edi, [eax+70h]
		add	edi, [ebp+70h]
		mov	[ebp+50h], esi
		mov	esi, [eax+58h]
		add	esi, [eax+18h]
		mov	[ebp+14h], edi
		mov	edi, [eax+74h]
		add	edi, [ebp+74h]
		mov	[ebp+48h], esi
		mov	esi, [eax+5Ch]
		add	esi, [eax+1Ch]
		mov	[ebp+4Ch], edi
		mov	edi, [eax+78h]
		add	edi, [ebp+60h]
		add	edx, ebx
		mov	[ebp+28h], edi
		mov	edi, [eax+7Ch]
		add	edi, [ebp+54h]
		mov	[ebp+3Ch], edi
		mov	edi, [eax+80h]
		add	edi, [ebp+5Ch]
		mov	[ebp+44h], edi
		mov	edi, [eax+4]
		mov	[ebp+58h], edi
		mov	edi, [eax+8]
		mov	[ebp-10h], edi
		mov	edi, [eax+0Ch]
		mov	[ebp-20h], edi
		mov	edi, ebx
		mov	[ebp+2Ch], edi
		mov	edi, [eax+14h]
		mov	[ebp-14h], edi
		mov	edi, [eax+18h]
		mov	[ebp-1Ch], edi
		mov	edi, [eax+1Ch]
		mov	[ebp+30h], edi
		mov	edi, [eax+20h]
		mov	[ebp+34h], edi
		mov	edi, [ebp+6Ch]
		rol	edi, 7
		xor	edi, [ebp+18h]
		mov	[ebp+0], edi
		mov	edi, [ebp+68h]
		rol	edi, 7
		xor	edi, [ebp+24h]
		mov	[ebp-4], edi
		mov	edi, [ebp+64h]
		rol	edi, 7
		xor	edi, ecx
		mov	[ebp+10h], edi
		mov	edi, [ebp+70h]
		rol	edi, 7
		xor	edi, edx
		mov	[ebp+0Ch], edi
		mov	edi, [ebp+74h]
		rol	edi, 7
		xor	edi, [ebp+50h]
		mov	[ebp-24h], edi
		mov	edi, [ebp+60h]
		rol	edi, 7
		xor	edi, [ebp+48h]
		mov	[ebp+1Ch], edi
		mov	edi, [ebp+54h]
		rol	edi, 7
		xor	edi, esi
		mov	[ebp+8], edi
		mov	edi, [ebp+5Ch]
		rol	edi, 7
		xor	edi, [ebp+40h]
		mov	[ebp+4], edi
		mov	edi, [ebp+58h]
		rol	edi, 7
		xor	edi, [ebp+20h]
		mov	[ebp+6Ch], edi
		mov	edi, [ebp-10h]
		rol	edi, 7
		xor	edi, [ebp-0Ch]
		mov	[ebp+68h], edi
		mov	edi, [ebp-20h]
		rol	edi, 7
		xor	edi, [ebp+38h]
		mov	[ebp+64h], edi
		mov	edi, ebx
		mov	ebx, [ebp+18h]
		rol	edi, 7
		xor	edi, [ebp+14h]
		mov	[ebp+58h], ebx
		mov	ebx, [ebp+24h]
		mov	[ebp+70h], edi
		mov	edi, [ebp-14h]
		rol	edi, 7
		xor	edi, [ebp+4Ch]
		mov	[ebp-8], ebx
		mov	ebx, [ebp+50h]
		mov	[ebp+74h], edi
		mov	edi, [ebp-1Ch]
		rol	edi, 7
		xor	edi, [ebp+28h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+48h]
		mov	[ebp+60h], edi
		mov	edi, [ebp+30h]
		rol	edi, 7
		xor	edi, [ebp+3Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+20h]
		mov	[ebp-20h], ebx
		mov	ebx, [ebp-0Ch]
		mov	[ebp+54h], edi
		mov	edi, [ebp+34h]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+4Ch]
		rol	edi, 7
		xor	edi, [ebp+44h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+28h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+0]
		add	ecx, ebx
		mov	[ebp+18h], ecx
		mov	ecx, [ebp-4]
		add	edx, ecx
		mov	ecx, [ebp+58h]
		mov	ebx, [ebp+8]
		mov	[ebp+24h], edx
		mov	edx, [ebp+10h]
		add	ecx, edx
		mov	edx, [ebp+0Ch]
		mov	[ebp-10h], ecx
		mov	ecx, [ebp-8]
		add	ecx, edx
		mov	edx, [ebp+1Ch]
		mov	[ebp-8], ecx
		mov	ecx, [ebp-24h]
		add	esi, ecx
		mov	[ebp+50h], esi
		mov	esi, [ebp+40h]
		add	esi, edx
		mov	[ebp+48h], esi
		mov	esi, [ebp-18h]
		add	esi, ebx
		mov	ebx, [ebp+4]
		mov	[ebp+58h], esi
		mov	esi, [ebp+5Ch]
		add	esi, ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp+40h], esi
		mov	esi, [ebp+38h]
		add	esi, ebx
		mov	ebx, [ebp+68h]
		mov	[ebp+20h], esi
		mov	esi, [ebp+14h]
		add	esi, ebx
		mov	ebx, [ebp+64h]
		mov	[ebp-0Ch], esi
		mov	esi, [ebp-20h]
		add	esi, ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+38h], esi
		mov	esi, [ebp+2Ch]
		add	esi, ebx
		mov	ebx, [ebp+74h]
		mov	[ebp+14h], esi
		mov	esi, [ebp+3Ch]
		add	esi, ebx
		mov	ebx, [ebp+60h]
		mov	[ebp+4Ch], esi
		mov	esi, [ebp+44h]
		add	esi, ebx
		mov	ebx, [ebp+30h]
		mov	[ebp+28h], esi
		mov	esi, [ebp+54h]
		add	ebx, esi
		mov	[ebp+3Ch], ebx
		mov	ebx, [ebp+34h]
		add	ebx, edi
		mov	[ebp+44h], ebx
		mov	ebx, [ebp+0]
		mov	[ebp+1Ch], ebx
		mov	ebx, [ebp-4]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+10h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+0Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp-14h], ebx
		mov	ebx, [ebp+68h]
		mov	[ebp-1Ch], ebx
		mov	ebx, [ebp+64h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+18h]
		rol	ecx, 0Bh
		xor	ecx, ebx
		mov	[ebp+0], ecx
		mov	ecx, [ebp+8]
		rol	edx, 0Bh
		xor	edx, [ebp+24h]
		rol	ecx, 0Bh
		xor	ecx, [ebp-10h]
		mov	[ebp-4], edx
		mov	[ebp+10h], ecx
		mov	ecx, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp-8]
		mov	edx, [ebp-0Ch]
		mov	[ebp+0Ch], ecx
		mov	ecx, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+50h]
		mov	[ebp-24h], ecx
		mov	ecx, [ebp+2Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+48h]
		mov	[ebp+1Ch], ecx
		mov	ecx, [ebp-18h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+58h]
		mov	[ebp+8], ecx
		mov	ecx, [ebp+5Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+40h]
		mov	[ebp+4], ecx
		mov	ecx, [ebp+74h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+20h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [ebp+60h]
		rol	ecx, 0Bh
		xor	ecx, edx
		rol	esi, 0Bh
		xor	esi, [ebp+38h]
		rol	edi, 0Bh
		mov	[ebp+68h], ecx
		mov	ecx, [ebp-14h]
		mov	[ebp+64h], esi
		mov	esi, [ebp+14h]
		xor	edi, esi
		mov	[ebp+70h], edi
		mov	edi, [ebp+0]
		mov	[eax+4], edi
		mov	edi, [ebp-4]
		mov	[eax+8], edi
		mov	edi, [ebp+10h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+4Ch]
		mov	[eax+0Ch], edi
		mov	edi, [ebp+0Ch]
		mov	[ebp+74h], ecx
		mov	ecx, [ebp-1Ch]
		mov	[eax+10h], edi
		mov	edi, [ebp-24h]
		mov	[eax+14h], edi
		mov	edi, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+28h]
		mov	[eax+18h], edi
		mov	edi, [ebp+8]
		mov	[ebp+60h], ecx
		mov	ecx, [ebp+30h]
		mov	[eax+1Ch], edi
		mov	edi, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp+3Ch]
		mov	[eax+20h], edi
		mov	edi, [ebp+6Ch]
		mov	[eax+24h], edi
		mov	edi, [ebp+68h]
		mov	[ebp+54h], ecx
		mov	ecx, [ebp+34h]
		mov	[eax+28h], edi
		mov	edi, [ebp+64h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+44h]
		mov	[eax+2Ch], edi
		mov	edi, [ebp+70h]
		mov	[eax+40h], ecx
		mov	ecx, [ebp+24h]
		mov	[eax+44h], ecx
		mov	ecx, [ebp-8]
		mov	[eax+4Ch], ecx
		mov	ecx, [ebp-10h]
		mov	[eax+50h], ecx
		mov	ecx, [ebp+48h]
		mov	[eax+54h], ecx
		mov	ecx, [ebp+50h]
		mov	[eax+58h], ecx
		mov	ecx, [ebp+40h]
		mov	[eax+5Ch], ecx
		mov	ecx, [ebp+58h]
		mov	[eax+60h], ecx
		mov	ecx, [ebp+20h]
		mov	[eax+68h], ecx
		mov	ecx, [ebp+38h]
		mov	[eax+70h], ecx
		mov	ecx, [ebp+28h]
		mov	[eax+30h], edi
		mov	edi, [ebp+74h]
		mov	[eax+74h], ecx
		mov	ecx, [ebp+4Ch]
		mov	[eax+34h], edi
		mov	edi, [ebp+60h]
		mov	[eax+78h], ecx
		mov	ecx, [ebp+44h]
		mov	[eax+38h], edi
		mov	edi, [ebp+54h]
		mov	[eax+7Ch], ecx
		mov	ecx, [ebp+3Ch]
		mov	[eax+3Ch], edi
		mov	[eax+48h], ebx
		mov	[eax+64h], edx
		mov	[eax+6Ch], esi
		mov	[eax+80h], ecx
		call	sub_407C40
		pop	edi
		pop	esi
		pop	ebx
		add	ebp, 78h
		leave
		retn

sub_4073D2:		; CODE XREF: sub_406F9B+42Ap


		push	ebp
		lea	ebp, [esp-78h]
		sub	esp, 9Ch
		mov	ecx, [eax+24h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [eax+28h]
		mov	edx, [eax+4]
		mov	[ebp+68h], ecx
		mov	ecx, [eax+2Ch]
		mov	[ebp+64h], ecx
		mov	ecx, [eax+30h]
		mov	[ebp+70h], ecx
		mov	ecx, [eax+34h]
		mov	[ebp+74h], ecx
		mov	ecx, [eax+38h]
		mov	[ebp+60h], ecx
		mov	ecx, [eax+3Ch]
		mov	[ebp+54h], ecx
		mov	ecx, [eax+40h]
		mov	[ebp+5Ch], ecx
		mov	ecx, [eax+44h]
		add	ecx, edx
		push	ebx
		push	esi
		mov	esi, [eax+8]
		push	edi
		mov	edi, [eax+0Ch]
		mov	[ebp+18h], ecx
		mov	ecx, [eax+48h]
		add	ecx, esi
		mov	[ebp+24h], ecx
		mov	ecx, [eax+4Ch]
		add	ecx, edi
		mov	edi, [eax+60h]
		add	edi, [eax+20h]
		mov	esi, [eax+54h]
		mov	[ebp+40h], edi
		mov	edi, [eax+64h]
		add	edi, [ebp+6Ch]
		add	esi, [eax+14h]
		mov	[ebp+20h], edi
		mov	edi, [eax+68h]
		add	edi, [ebp+68h]
		mov	ebx, [eax+10h]
		mov	[ebp-0Ch], edi
		mov	edi, [eax+6Ch]
		add	edi, [ebp+64h]
		mov	edx, [eax+50h]
		mov	[ebp+38h], edi
		mov	edi, [eax+70h]
		add	edi, [ebp+70h]
		mov	[ebp+50h], esi
		mov	esi, [eax+58h]
		add	esi, [eax+18h]
		mov	[ebp+14h], edi
		mov	edi, [eax+74h]
		add	edi, [ebp+74h]
		mov	[ebp+48h], esi
		mov	esi, [eax+5Ch]
		add	esi, [eax+1Ch]
		mov	[ebp+4Ch], edi
		mov	edi, [eax+78h]
		add	edi, [ebp+60h]
		add	edx, ebx
		mov	[ebp+28h], edi
		mov	edi, [eax+7Ch]
		add	edi, [ebp+54h]
		mov	[ebp+3Ch], edi
		mov	edi, [eax+80h]
		add	edi, [ebp+5Ch]
		mov	[ebp+44h], edi
		mov	edi, [eax+4]
		mov	[ebp+58h], edi
		mov	edi, [eax+8]
		mov	[ebp-10h], edi
		mov	edi, [eax+0Ch]
		mov	[ebp-20h], edi
		mov	edi, ebx
		mov	[ebp+2Ch], edi
		mov	edi, [eax+14h]
		mov	[ebp-14h], edi
		mov	edi, [eax+18h]
		mov	[ebp-1Ch], edi
		mov	edi, [eax+1Ch]
		mov	[ebp+30h], edi
		mov	edi, [eax+20h]
		mov	[ebp+34h], edi
		mov	edi, [ebp+6Ch]
		rol	edi, 7
		xor	edi, [ebp+18h]
		mov	[ebp+0], edi
		mov	edi, [ebp+68h]
		rol	edi, 7
		xor	edi, [ebp+24h]
		mov	[ebp-4], edi
		mov	edi, [ebp+64h]
		rol	edi, 7
		xor	edi, ecx
		mov	[ebp+10h], edi
		mov	edi, [ebp+70h]
		rol	edi, 7
		xor	edi, edx
		mov	[ebp+0Ch], edi
		mov	edi, [ebp+74h]
		rol	edi, 7
		xor	edi, [ebp+50h]
		mov	[ebp-24h], edi
		mov	edi, [ebp+60h]
		rol	edi, 7
		xor	edi, [ebp+48h]
		mov	[ebp+1Ch], edi
		mov	edi, [ebp+54h]
		rol	edi, 7
		xor	edi, esi
		mov	[ebp+8], edi
		mov	edi, [ebp+5Ch]
		rol	edi, 7
		xor	edi, [ebp+40h]
		mov	[ebp+4], edi
		mov	edi, [ebp+58h]
		rol	edi, 7
		xor	edi, [ebp+20h]
		mov	[ebp+6Ch], edi
		mov	edi, [ebp-10h]
		rol	edi, 7
		xor	edi, [ebp-0Ch]
		mov	[ebp+68h], edi
		mov	edi, [ebp-20h]
		rol	edi, 7
		xor	edi, [ebp+38h]
		mov	[ebp+64h], edi
		mov	edi, ebx
		mov	ebx, [ebp+18h]
		rol	edi, 7
		xor	edi, [ebp+14h]
		mov	[ebp+58h], ebx
		mov	ebx, [ebp+24h]
		mov	[ebp+70h], edi
		mov	edi, [ebp-14h]
		rol	edi, 7
		xor	edi, [ebp+4Ch]
		mov	[ebp-8], ebx
		mov	ebx, [ebp+50h]
		mov	[ebp+74h], edi
		mov	edi, [ebp-1Ch]
		rol	edi, 7
		xor	edi, [ebp+28h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+48h]
		mov	[ebp+60h], edi
		mov	edi, [ebp+30h]
		rol	edi, 7
		xor	edi, [ebp+3Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+20h]
		mov	[ebp-20h], ebx
		mov	ebx, [ebp-0Ch]
		mov	[ebp+54h], edi
		mov	edi, [ebp+34h]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+4Ch]
		rol	edi, 7
		xor	edi, [ebp+44h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+28h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+0]
		add	ecx, ebx
		mov	[ebp+18h], ecx
		mov	ecx, [ebp-4]
		add	edx, ecx
		mov	ecx, [ebp+58h]
		mov	ebx, [ebp+8]
		mov	[ebp+24h], edx
		mov	edx, [ebp+10h]
		add	ecx, edx
		mov	edx, [ebp+0Ch]
		mov	[ebp-10h], ecx
		mov	ecx, [ebp-8]
		add	ecx, edx
		mov	edx, [ebp+1Ch]
		mov	[ebp-8], ecx
		mov	ecx, [ebp-24h]
		add	esi, ecx
		mov	[ebp+50h], esi
		mov	esi, [ebp+40h]
		add	esi, edx
		mov	[ebp+48h], esi
		mov	esi, [ebp-18h]
		add	esi, ebx
		mov	ebx, [ebp+4]
		mov	[ebp+58h], esi
		mov	esi, [ebp+5Ch]
		add	esi, ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp+40h], esi
		mov	esi, [ebp+38h]
		add	esi, ebx
		mov	ebx, [ebp+68h]
		mov	[ebp+20h], esi
		mov	esi, [ebp+14h]
		add	esi, ebx
		mov	ebx, [ebp+64h]
		mov	[ebp-0Ch], esi
		mov	esi, [ebp-20h]
		add	esi, ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+38h], esi
		mov	esi, [ebp+2Ch]
		add	esi, ebx
		mov	ebx, [ebp+74h]
		mov	[ebp+14h], esi
		mov	esi, [ebp+3Ch]
		add	esi, ebx
		mov	ebx, [ebp+60h]
		mov	[ebp+4Ch], esi
		mov	esi, [ebp+44h]
		add	esi, ebx
		mov	ebx, [ebp+30h]
		mov	[ebp+28h], esi
		mov	esi, [ebp+54h]
		add	ebx, esi
		mov	[ebp+3Ch], ebx
		mov	ebx, [ebp+34h]
		add	ebx, edi
		mov	[ebp+44h], ebx
		mov	ebx, [ebp+0]
		mov	[ebp+1Ch], ebx
		mov	ebx, [ebp-4]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+10h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+0Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp-14h], ebx
		mov	ebx, [ebp+68h]
		mov	[ebp-1Ch], ebx
		mov	ebx, [ebp+64h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+18h]
		rol	ecx, 0Bh
		xor	ecx, ebx
		mov	[ebp+0], ecx
		mov	ecx, [ebp+8]
		rol	edx, 0Bh
		xor	edx, [ebp+24h]
		rol	ecx, 0Bh
		xor	ecx, [ebp-10h]
		mov	[ebp-4], edx
		mov	[ebp+10h], ecx
		mov	ecx, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp-8]
		mov	edx, [ebp-0Ch]
		mov	[ebp+0Ch], ecx
		mov	ecx, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+50h]
		mov	[ebp-24h], ecx
		mov	ecx, [ebp+2Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+48h]
		mov	[ebp+1Ch], ecx
		mov	ecx, [ebp-18h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+58h]
		mov	[ebp+8], ecx
		mov	ecx, [ebp+5Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+40h]
		mov	[ebp+4], ecx
		mov	ecx, [ebp+74h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+20h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [ebp+60h]
		rol	ecx, 0Bh
		xor	ecx, edx
		rol	esi, 0Bh
		xor	esi, [ebp+38h]
		rol	edi, 0Bh
		mov	[ebp+68h], ecx
		mov	ecx, [ebp-14h]
		mov	[ebp+64h], esi
		mov	esi, [ebp+14h]
		xor	edi, esi
		mov	[ebp+70h], edi
		mov	edi, [ebp+0]
		mov	[eax+4], edi
		mov	edi, [ebp-4]
		mov	[eax+8], edi
		mov	edi, [ebp+10h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+4Ch]
		mov	[eax+0Ch], edi
		mov	edi, [ebp+0Ch]
		mov	[ebp+74h], ecx
		mov	ecx, [ebp-1Ch]
		mov	[eax+10h], edi
		mov	edi, [ebp-24h]
		mov	[eax+14h], edi
		mov	edi, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+28h]
		mov	[eax+18h], edi
		mov	edi, [ebp+8]
		mov	[ebp+60h], ecx
		mov	ecx, [ebp+30h]
		mov	[eax+1Ch], edi
		mov	edi, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp+3Ch]
		mov	[eax+20h], edi
		mov	edi, [ebp+6Ch]
		mov	[eax+24h], edi
		mov	edi, [ebp+68h]
		mov	[ebp+54h], ecx
		mov	ecx, [ebp+34h]
		mov	[eax+28h], edi
		mov	edi, [ebp+64h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+44h]
		mov	[eax+2Ch], edi
		mov	edi, [ebp+70h]
		mov	[eax+40h], ecx
		mov	ecx, [ebp+24h]
		mov	[eax+44h], ecx
		mov	ecx, [ebp-8]
		mov	[eax+4Ch], ecx
		mov	ecx, [ebp-10h]
		mov	[eax+50h], ecx
		mov	ecx, [ebp+48h]
		mov	[eax+54h], ecx
		mov	ecx, [ebp+50h]
		mov	[eax+58h], ecx
		mov	ecx, [ebp+40h]
		mov	[eax+5Ch], ecx
		mov	ecx, [ebp+58h]
		mov	[eax+60h], ecx
		mov	ecx, [ebp+20h]
		mov	[eax+68h], ecx
		mov	ecx, [ebp+38h]
		mov	[eax+70h], ecx
		mov	ecx, [ebp+28h]
		mov	[eax+30h], edi
		mov	edi, [ebp+74h]
		mov	[eax+74h], ecx
		mov	ecx, [ebp+4Ch]
		mov	[eax+34h], edi
		mov	edi, [ebp+60h]
		mov	[eax+78h], ecx
		mov	ecx, [ebp+44h]
		mov	[eax+38h], edi
		mov	edi, [ebp+54h]
		mov	[eax+7Ch], ecx
		mov	ecx, [ebp+3Ch]
		mov	[eax+3Ch], edi
		mov	[eax+48h], ebx
		mov	[eax+64h], edx
		mov	[eax+6Ch], esi
		mov	[eax+80h], ecx
		call	sub_407809
		pop	edi
		pop	esi
		pop	ebx
		add	ebp, 78h
		leave
		retn

sub_406F9B:		; CODE XREF: sub_406AEC+42Ap


		push	ebp
		lea	ebp, [esp-78h]
		sub	esp, 9Ch
		mov	ecx, [eax+24h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [eax+28h]
		mov	edx, [eax+4]
		mov	[ebp+68h], ecx
		mov	ecx, [eax+2Ch]
		mov	[ebp+64h], ecx
		mov	ecx, [eax+30h]
		mov	[ebp+70h], ecx
		mov	ecx, [eax+34h]
		mov	[ebp+74h], ecx
		mov	ecx, [eax+38h]
		mov	[ebp+60h], ecx
		mov	ecx, [eax+3Ch]
		mov	[ebp+54h], ecx
		mov	ecx, [eax+40h]
		mov	[ebp+5Ch], ecx
		mov	ecx, [eax+44h]
		add	ecx, edx
		push	ebx
		push	esi
		mov	esi, [eax+8]
		push	edi
		mov	edi, [eax+0Ch]
		mov	[ebp+18h], ecx
		mov	ecx, [eax+48h]
		add	ecx, esi
		mov	[ebp+24h], ecx
		mov	ecx, [eax+4Ch]
		add	ecx, edi
		mov	edi, [eax+60h]
		add	edi, [eax+20h]
		mov	esi, [eax+54h]
		mov	[ebp+40h], edi
		mov	edi, [eax+64h]
		add	edi, [ebp+6Ch]
		add	esi, [eax+14h]
		mov	[ebp+20h], edi
		mov	edi, [eax+68h]
		add	edi, [ebp+68h]
		mov	ebx, [eax+10h]
		mov	[ebp-0Ch], edi
		mov	edi, [eax+6Ch]
		add	edi, [ebp+64h]
		mov	edx, [eax+50h]
		mov	[ebp+38h], edi
		mov	edi, [eax+70h]
		add	edi, [ebp+70h]
		mov	[ebp+50h], esi
		mov	esi, [eax+58h]
		add	esi, [eax+18h]
		mov	[ebp+14h], edi
		mov	edi, [eax+74h]
		add	edi, [ebp+74h]
		mov	[ebp+48h], esi
		mov	esi, [eax+5Ch]
		add	esi, [eax+1Ch]
		mov	[ebp+4Ch], edi
		mov	edi, [eax+78h]
		add	edi, [ebp+60h]
		add	edx, ebx
		mov	[ebp+28h], edi
		mov	edi, [eax+7Ch]
		add	edi, [ebp+54h]
		mov	[ebp+3Ch], edi
		mov	edi, [eax+80h]
		add	edi, [ebp+5Ch]
		mov	[ebp+44h], edi
		mov	edi, [eax+4]
		mov	[ebp+58h], edi
		mov	edi, [eax+8]
		mov	[ebp-10h], edi
		mov	edi, [eax+0Ch]
		mov	[ebp-20h], edi
		mov	edi, ebx
		mov	[ebp+2Ch], edi
		mov	edi, [eax+14h]
		mov	[ebp-14h], edi
		mov	edi, [eax+18h]
		mov	[ebp-1Ch], edi
		mov	edi, [eax+1Ch]
		mov	[ebp+30h], edi
		mov	edi, [eax+20h]
		mov	[ebp+34h], edi
		mov	edi, [ebp+6Ch]
		rol	edi, 7
		xor	edi, [ebp+18h]
		mov	[ebp+0], edi
		mov	edi, [ebp+68h]
		rol	edi, 7
		xor	edi, [ebp+24h]
		mov	[ebp-4], edi
		mov	edi, [ebp+64h]
		rol	edi, 7
		xor	edi, ecx
		mov	[ebp+10h], edi
		mov	edi, [ebp+70h]
		rol	edi, 7
		xor	edi, edx
		mov	[ebp+0Ch], edi
		mov	edi, [ebp+74h]
		rol	edi, 7
		xor	edi, [ebp+50h]
		mov	[ebp-24h], edi
		mov	edi, [ebp+60h]
		rol	edi, 7
		xor	edi, [ebp+48h]
		mov	[ebp+1Ch], edi
		mov	edi, [ebp+54h]
		rol	edi, 7
		xor	edi, esi
		mov	[ebp+8], edi
		mov	edi, [ebp+5Ch]
		rol	edi, 7
		xor	edi, [ebp+40h]
		mov	[ebp+4], edi
		mov	edi, [ebp+58h]
		rol	edi, 7
		xor	edi, [ebp+20h]
		mov	[ebp+6Ch], edi
		mov	edi, [ebp-10h]
		rol	edi, 7
		xor	edi, [ebp-0Ch]
		mov	[ebp+68h], edi
		mov	edi, [ebp-20h]
		rol	edi, 7
		xor	edi, [ebp+38h]
		mov	[ebp+64h], edi
		mov	edi, ebx
		mov	ebx, [ebp+18h]
		rol	edi, 7
		xor	edi, [ebp+14h]
		mov	[ebp+58h], ebx
		mov	ebx, [ebp+24h]
		mov	[ebp+70h], edi
		mov	edi, [ebp-14h]
		rol	edi, 7
		xor	edi, [ebp+4Ch]
		mov	[ebp-8], ebx
		mov	ebx, [ebp+50h]
		mov	[ebp+74h], edi
		mov	edi, [ebp-1Ch]
		rol	edi, 7
		xor	edi, [ebp+28h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+48h]
		mov	[ebp+60h], edi
		mov	edi, [ebp+30h]
		rol	edi, 7
		xor	edi, [ebp+3Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+20h]
		mov	[ebp-20h], ebx
		mov	ebx, [ebp-0Ch]
		mov	[ebp+54h], edi
		mov	edi, [ebp+34h]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+4Ch]
		rol	edi, 7
		xor	edi, [ebp+44h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+28h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+0]
		add	ecx, ebx
		mov	[ebp+18h], ecx
		mov	ecx, [ebp-4]
		add	edx, ecx
		mov	ecx, [ebp+58h]
		mov	ebx, [ebp+8]
		mov	[ebp+24h], edx
		mov	edx, [ebp+10h]
		add	ecx, edx
		mov	edx, [ebp+0Ch]
		mov	[ebp-10h], ecx
		mov	ecx, [ebp-8]
		add	ecx, edx
		mov	edx, [ebp+1Ch]
		mov	[ebp-8], ecx
		mov	ecx, [ebp-24h]
		add	esi, ecx
		mov	[ebp+50h], esi
		mov	esi, [ebp+40h]
		add	esi, edx
		mov	[ebp+48h], esi
		mov	esi, [ebp-18h]
		add	esi, ebx
		mov	ebx, [ebp+4]
		mov	[ebp+58h], esi
		mov	esi, [ebp+5Ch]
		add	esi, ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp+40h], esi
		mov	esi, [ebp+38h]
		add	esi, ebx
		mov	ebx, [ebp+68h]
		mov	[ebp+20h], esi
		mov	esi, [ebp+14h]
		add	esi, ebx
		mov	ebx, [ebp+64h]
		mov	[ebp-0Ch], esi
		mov	esi, [ebp-20h]
		add	esi, ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+38h], esi
		mov	esi, [ebp+2Ch]
		add	esi, ebx
		mov	ebx, [ebp+74h]
		mov	[ebp+14h], esi
		mov	esi, [ebp+3Ch]
		add	esi, ebx
		mov	ebx, [ebp+60h]
		mov	[ebp+4Ch], esi
		mov	esi, [ebp+44h]
		add	esi, ebx
		mov	ebx, [ebp+30h]
		mov	[ebp+28h], esi
		mov	esi, [ebp+54h]
		add	ebx, esi
		mov	[ebp+3Ch], ebx
		mov	ebx, [ebp+34h]
		add	ebx, edi
		mov	[ebp+44h], ebx
		mov	ebx, [ebp+0]
		mov	[ebp+1Ch], ebx
		mov	ebx, [ebp-4]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+10h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+0Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp-14h], ebx
		mov	ebx, [ebp+68h]
		mov	[ebp-1Ch], ebx
		mov	ebx, [ebp+64h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+18h]
		rol	ecx, 0Bh
		xor	ecx, ebx
		mov	[ebp+0], ecx
		mov	ecx, [ebp+8]
		rol	edx, 0Bh
		xor	edx, [ebp+24h]
		rol	ecx, 0Bh
		xor	ecx, [ebp-10h]
		mov	[ebp-4], edx
		mov	[ebp+10h], ecx
		mov	ecx, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp-8]
		mov	edx, [ebp-0Ch]
		mov	[ebp+0Ch], ecx
		mov	ecx, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+50h]
		mov	[ebp-24h], ecx
		mov	ecx, [ebp+2Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+48h]
		mov	[ebp+1Ch], ecx
		mov	ecx, [ebp-18h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+58h]
		mov	[ebp+8], ecx
		mov	ecx, [ebp+5Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+40h]
		mov	[ebp+4], ecx
		mov	ecx, [ebp+74h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+20h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [ebp+60h]
		rol	ecx, 0Bh
		xor	ecx, edx
		rol	esi, 0Bh
		xor	esi, [ebp+38h]
		rol	edi, 0Bh
		mov	[ebp+68h], ecx
		mov	ecx, [ebp-14h]
		mov	[ebp+64h], esi
		mov	esi, [ebp+14h]
		xor	edi, esi
		mov	[ebp+70h], edi
		mov	edi, [ebp+0]
		mov	[eax+4], edi
		mov	edi, [ebp-4]
		mov	[eax+8], edi
		mov	edi, [ebp+10h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+4Ch]
		mov	[eax+0Ch], edi
		mov	edi, [ebp+0Ch]
		mov	[ebp+74h], ecx
		mov	ecx, [ebp-1Ch]
		mov	[eax+10h], edi
		mov	edi, [ebp-24h]
		mov	[eax+14h], edi
		mov	edi, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+28h]
		mov	[eax+18h], edi
		mov	edi, [ebp+8]
		mov	[ebp+60h], ecx
		mov	ecx, [ebp+30h]
		mov	[eax+1Ch], edi
		mov	edi, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp+3Ch]
		mov	[eax+20h], edi
		mov	edi, [ebp+6Ch]
		mov	[eax+24h], edi
		mov	edi, [ebp+68h]
		mov	[ebp+54h], ecx
		mov	ecx, [ebp+34h]
		mov	[eax+28h], edi
		mov	edi, [ebp+64h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+44h]
		mov	[eax+2Ch], edi
		mov	edi, [ebp+70h]
		mov	[eax+40h], ecx
		mov	ecx, [ebp+24h]
		mov	[eax+44h], ecx
		mov	ecx, [ebp-8]
		mov	[eax+4Ch], ecx
		mov	ecx, [ebp-10h]
		mov	[eax+50h], ecx
		mov	ecx, [ebp+48h]
		mov	[eax+54h], ecx
		mov	ecx, [ebp+50h]
		mov	[eax+58h], ecx
		mov	ecx, [ebp+40h]
		mov	[eax+5Ch], ecx
		mov	ecx, [ebp+58h]
		mov	[eax+60h], ecx
		mov	ecx, [ebp+20h]
		mov	[eax+68h], ecx
		mov	ecx, [ebp+38h]
		mov	[eax+70h], ecx
		mov	ecx, [ebp+28h]
		mov	[eax+30h], edi
		mov	edi, [ebp+74h]
		mov	[eax+74h], ecx
		mov	ecx, [ebp+4Ch]
		mov	[eax+34h], edi
		mov	edi, [ebp+60h]
		mov	[eax+78h], ecx
		mov	ecx, [ebp+44h]
		mov	[eax+38h], edi
		mov	edi, [ebp+54h]
		mov	[eax+7Ch], ecx
		mov	ecx, [ebp+3Ch]
		mov	[eax+3Ch], edi
		mov	[eax+48h], ebx
		mov	[eax+64h], edx
		mov	[eax+6Ch], esi
		mov	[eax+80h], ecx
		call	sub_4073D2
		pop	edi
		pop	esi
		pop	ebx
		add	ebp, 78h
		leave
		retn

sub_406AEC:		; CODE XREF: sub_406605+42Ap


		push	ebp
		lea	ebp, [esp-78h]
		sub	esp, 9Ch
		mov	ecx, [eax+24h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [eax+28h]
		mov	edx, [eax+4]
		mov	[ebp+68h], ecx
		mov	ecx, [eax+2Ch]
		mov	[ebp+64h], ecx
		mov	ecx, [eax+30h]
		mov	[ebp+70h], ecx
		mov	ecx, [eax+34h]
		mov	[ebp+74h], ecx
		mov	ecx, [eax+38h]
		mov	[ebp+60h], ecx
		mov	ecx, [eax+3Ch]
		mov	[ebp+54h], ecx
		mov	ecx, [eax+40h]
		mov	[ebp+5Ch], ecx
		mov	ecx, [eax+44h]
		add	ecx, edx
		push	ebx
		push	esi
		mov	esi, [eax+8]
		push	edi
		mov	edi, [eax+0Ch]
		mov	[ebp+18h], ecx
		mov	ecx, [eax+48h]
		add	ecx, esi
		mov	[ebp+24h], ecx
		mov	ecx, [eax+4Ch]
		add	ecx, edi
		mov	edi, [eax+60h]
		add	edi, [eax+20h]
		mov	esi, [eax+54h]
		mov	[ebp+40h], edi
		mov	edi, [eax+64h]
		add	edi, [ebp+6Ch]
		add	esi, [eax+14h]
		mov	[ebp+20h], edi
		mov	edi, [eax+68h]
		add	edi, [ebp+68h]
		mov	ebx, [eax+10h]
		mov	[ebp-0Ch], edi
		mov	edi, [eax+6Ch]
		add	edi, [ebp+64h]
		mov	edx, [eax+50h]
		mov	[ebp+38h], edi
		mov	edi, [eax+70h]
		add	edi, [ebp+70h]
		mov	[ebp+50h], esi
		mov	esi, [eax+58h]
		add	esi, [eax+18h]
		mov	[ebp+14h], edi
		mov	edi, [eax+74h]
		add	edi, [ebp+74h]
		mov	[ebp+48h], esi
		mov	esi, [eax+5Ch]
		add	esi, [eax+1Ch]
		mov	[ebp+4Ch], edi
		mov	edi, [eax+78h]
		add	edi, [ebp+60h]
		add	edx, ebx
		mov	[ebp+28h], edi
		mov	edi, [eax+7Ch]
		add	edi, [ebp+54h]
		mov	[ebp+3Ch], edi
		mov	edi, [eax+80h]
		add	edi, [ebp+5Ch]
		mov	[ebp+44h], edi
		mov	edi, [eax+4]
		mov	[ebp+58h], edi
		mov	edi, [eax+8]
		mov	[ebp-10h], edi
		mov	edi, [eax+0Ch]
		mov	[ebp-20h], edi
		mov	edi, ebx
		mov	[ebp+2Ch], edi
		mov	edi, [eax+14h]
		mov	[ebp-14h], edi
		mov	edi, [eax+18h]
		mov	[ebp-1Ch], edi
		mov	edi, [eax+1Ch]
		mov	[ebp+30h], edi
		mov	edi, [eax+20h]
		mov	[ebp+34h], edi
		mov	edi, [ebp+6Ch]
		rol	edi, 7
		xor	edi, [ebp+18h]
		mov	[ebp+0], edi
		mov	edi, [ebp+68h]
		rol	edi, 7
		xor	edi, [ebp+24h]
		mov	[ebp-4], edi
		mov	edi, [ebp+64h]
		rol	edi, 7
		xor	edi, ecx
		mov	[ebp+10h], edi
		mov	edi, [ebp+70h]
		rol	edi, 7
		xor	edi, edx
		mov	[ebp+0Ch], edi
		mov	edi, [ebp+74h]
		rol	edi, 7
		xor	edi, [ebp+50h]
		mov	[ebp-24h], edi
		mov	edi, [ebp+60h]
		rol	edi, 7
		xor	edi, [ebp+48h]
		mov	[ebp+1Ch], edi
		mov	edi, [ebp+54h]
		rol	edi, 7
		xor	edi, esi
		mov	[ebp+8], edi
		mov	edi, [ebp+5Ch]
		rol	edi, 7
		xor	edi, [ebp+40h]
		mov	[ebp+4], edi
		mov	edi, [ebp+58h]
		rol	edi, 7
		xor	edi, [ebp+20h]
		mov	[ebp+6Ch], edi
		mov	edi, [ebp-10h]
		rol	edi, 7
		xor	edi, [ebp-0Ch]
		mov	[ebp+68h], edi
		mov	edi, [ebp-20h]
		rol	edi, 7
		xor	edi, [ebp+38h]
		mov	[ebp+64h], edi
		mov	edi, ebx
		mov	ebx, [ebp+18h]
		rol	edi, 7
		xor	edi, [ebp+14h]
		mov	[ebp+58h], ebx
		mov	ebx, [ebp+24h]
		mov	[ebp+70h], edi
		mov	edi, [ebp-14h]
		rol	edi, 7
		xor	edi, [ebp+4Ch]
		mov	[ebp-8], ebx
		mov	ebx, [ebp+50h]
		mov	[ebp+74h], edi
		mov	edi, [ebp-1Ch]
		rol	edi, 7
		xor	edi, [ebp+28h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+48h]
		mov	[ebp+60h], edi
		mov	edi, [ebp+30h]
		rol	edi, 7
		xor	edi, [ebp+3Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+20h]
		mov	[ebp-20h], ebx
		mov	ebx, [ebp-0Ch]
		mov	[ebp+54h], edi
		mov	edi, [ebp+34h]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+4Ch]
		rol	edi, 7
		xor	edi, [ebp+44h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+28h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+0]
		add	ecx, ebx
		mov	[ebp+18h], ecx
		mov	ecx, [ebp-4]
		add	edx, ecx
		mov	ecx, [ebp+58h]
		mov	ebx, [ebp+8]
		mov	[ebp+24h], edx
		mov	edx, [ebp+10h]
		add	ecx, edx
		mov	edx, [ebp+0Ch]
		mov	[ebp-10h], ecx
		mov	ecx, [ebp-8]
		add	ecx, edx
		mov	edx, [ebp+1Ch]
		mov	[ebp-8], ecx
		mov	ecx, [ebp-24h]
		add	esi, ecx
		mov	[ebp+50h], esi
		mov	esi, [ebp+40h]
		add	esi, edx
		mov	[ebp+48h], esi
		mov	esi, [ebp-18h]
		add	esi, ebx
		mov	ebx, [ebp+4]
		mov	[ebp+58h], esi
		mov	esi, [ebp+5Ch]
		add	esi, ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp+40h], esi
		mov	esi, [ebp+38h]
		add	esi, ebx
		mov	ebx, [ebp+68h]
		mov	[ebp+20h], esi
		mov	esi, [ebp+14h]
		add	esi, ebx
		mov	ebx, [ebp+64h]
		mov	[ebp-0Ch], esi
		mov	esi, [ebp-20h]
		add	esi, ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+38h], esi
		mov	esi, [ebp+2Ch]
		add	esi, ebx
		mov	ebx, [ebp+74h]
		mov	[ebp+14h], esi
		mov	esi, [ebp+3Ch]
		add	esi, ebx
		mov	ebx, [ebp+60h]
		mov	[ebp+4Ch], esi
		mov	esi, [ebp+44h]
		add	esi, ebx
		mov	ebx, [ebp+30h]
		mov	[ebp+28h], esi
		mov	esi, [ebp+54h]
		add	ebx, esi
		mov	[ebp+3Ch], ebx
		mov	ebx, [ebp+34h]
		add	ebx, edi
		mov	[ebp+44h], ebx
		mov	ebx, [ebp+0]
		mov	[ebp+1Ch], ebx
		mov	ebx, [ebp-4]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+10h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+0Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp-14h], ebx
		mov	ebx, [ebp+68h]
		mov	[ebp-1Ch], ebx
		mov	ebx, [ebp+64h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+18h]
		rol	ecx, 0Bh
		xor	ecx, ebx
		mov	[ebp+0], ecx
		mov	ecx, [ebp+8]
		rol	edx, 0Bh
		xor	edx, [ebp+24h]
		rol	ecx, 0Bh
		xor	ecx, [ebp-10h]
		mov	[ebp-4], edx
		mov	[ebp+10h], ecx
		mov	ecx, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp-8]
		mov	edx, [ebp-0Ch]
		mov	[ebp+0Ch], ecx
		mov	ecx, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+50h]
		mov	[ebp-24h], ecx
		mov	ecx, [ebp+2Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+48h]
		mov	[ebp+1Ch], ecx
		mov	ecx, [ebp-18h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+58h]
		mov	[ebp+8], ecx
		mov	ecx, [ebp+5Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+40h]
		mov	[ebp+4], ecx
		mov	ecx, [ebp+74h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+20h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [ebp+60h]
		rol	ecx, 0Bh
		xor	ecx, edx
		rol	esi, 0Bh
		xor	esi, [ebp+38h]
		rol	edi, 0Bh
		mov	[ebp+68h], ecx
		mov	ecx, [ebp-14h]
		mov	[ebp+64h], esi
		mov	esi, [ebp+14h]
		xor	edi, esi
		mov	[ebp+70h], edi
		mov	edi, [ebp+0]
		mov	[eax+4], edi
		mov	edi, [ebp-4]
		mov	[eax+8], edi
		mov	edi, [ebp+10h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+4Ch]
		mov	[eax+0Ch], edi
		mov	edi, [ebp+0Ch]
		mov	[ebp+74h], ecx
		mov	ecx, [ebp-1Ch]
		mov	[eax+10h], edi
		mov	edi, [ebp-24h]
		mov	[eax+14h], edi
		mov	edi, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+28h]
		mov	[eax+18h], edi
		mov	edi, [ebp+8]
		mov	[ebp+60h], ecx
		mov	ecx, [ebp+30h]
		mov	[eax+1Ch], edi
		mov	edi, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp+3Ch]
		mov	[eax+20h], edi
		mov	edi, [ebp+6Ch]
		mov	[eax+24h], edi
		mov	edi, [ebp+68h]
		mov	[ebp+54h], ecx
		mov	ecx, [ebp+34h]
		mov	[eax+28h], edi
		mov	edi, [ebp+64h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+44h]
		mov	[eax+2Ch], edi
		mov	edi, [ebp+70h]
		mov	[eax+40h], ecx
		mov	ecx, [ebp+24h]
		mov	[eax+44h], ecx
		mov	ecx, [ebp-8]
		mov	[eax+4Ch], ecx
		mov	ecx, [ebp-10h]
		mov	[eax+50h], ecx
		mov	ecx, [ebp+48h]
		mov	[eax+54h], ecx
		mov	ecx, [ebp+50h]
		mov	[eax+58h], ecx
		mov	ecx, [ebp+40h]
		mov	[eax+5Ch], ecx
		mov	ecx, [ebp+58h]
		mov	[eax+60h], ecx
		mov	ecx, [ebp+20h]
		mov	[eax+68h], ecx
		mov	ecx, [ebp+38h]
		mov	[eax+70h], ecx
		mov	ecx, [ebp+28h]
		mov	[eax+30h], edi
		mov	edi, [ebp+74h]
		mov	[eax+74h], ecx
		mov	ecx, [ebp+4Ch]
		mov	[eax+34h], edi
		mov	edi, [ebp+60h]
		mov	[eax+78h], ecx
		mov	ecx, [ebp+44h]
		mov	[eax+38h], edi
		mov	edi, [ebp+54h]
		mov	[eax+7Ch], ecx
		mov	ecx, [ebp+3Ch]
		mov	[eax+3Ch], edi
		mov	[eax+48h], ebx
		mov	[eax+64h], edx
		mov	[eax+6Ch], esi
		mov	[eax+80h], ecx
		call	sub_406F9B
		pop	edi
		pop	esi
		pop	ebx
		add	ebp, 78h
		leave
		retn

sub_406605:		; CODE XREF: sub_405D42+42Ap


		push	ebp
		lea	ebp, [esp-78h]
		sub	esp, 9Ch
		mov	ecx, [eax+24h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [eax+28h]
		mov	edx, [eax+4]
		mov	[ebp+68h], ecx
		mov	ecx, [eax+2Ch]
		mov	[ebp+64h], ecx
		mov	ecx, [eax+30h]
		mov	[ebp+70h], ecx
		mov	ecx, [eax+34h]
		mov	[ebp+74h], ecx
		mov	ecx, [eax+38h]
		mov	[ebp+60h], ecx
		mov	ecx, [eax+3Ch]
		mov	[ebp+54h], ecx
		mov	ecx, [eax+40h]
		mov	[ebp+5Ch], ecx
		mov	ecx, [eax+44h]
		add	ecx, edx
		push	ebx
		push	esi
		mov	esi, [eax+8]
		push	edi
		mov	edi, [eax+0Ch]
		mov	[ebp+18h], ecx
		mov	ecx, [eax+48h]
		add	ecx, esi
		mov	[ebp+24h], ecx
		mov	ecx, [eax+4Ch]
		add	ecx, edi
		mov	edi, [eax+60h]
		add	edi, [eax+20h]
		mov	esi, [eax+54h]
		mov	[ebp+40h], edi
		mov	edi, [eax+64h]
		add	edi, [ebp+6Ch]
		add	esi, [eax+14h]
		mov	[ebp+20h], edi
		mov	edi, [eax+68h]
		add	edi, [ebp+68h]
		mov	ebx, [eax+10h]
		mov	[ebp-0Ch], edi
		mov	edi, [eax+6Ch]
		add	edi, [ebp+64h]
		mov	edx, [eax+50h]
		mov	[ebp+38h], edi
		mov	edi, [eax+70h]
		add	edi, [ebp+70h]
		mov	[ebp+50h], esi
		mov	esi, [eax+58h]
		add	esi, [eax+18h]
		mov	[ebp+14h], edi
		mov	edi, [eax+74h]
		add	edi, [ebp+74h]
		mov	[ebp+48h], esi
		mov	esi, [eax+5Ch]
		add	esi, [eax+1Ch]
		mov	[ebp+4Ch], edi
		mov	edi, [eax+78h]
		add	edi, [ebp+60h]
		add	edx, ebx
		mov	[ebp+28h], edi
		mov	edi, [eax+7Ch]
		add	edi, [ebp+54h]
		mov	[ebp+3Ch], edi
		mov	edi, [eax+80h]
		add	edi, [ebp+5Ch]
		mov	[ebp+44h], edi
		mov	edi, [eax+4]
		mov	[ebp+58h], edi
		mov	edi, [eax+8]
		mov	[ebp-10h], edi
		mov	edi, [eax+0Ch]
		mov	[ebp-20h], edi
		mov	edi, ebx
		mov	[ebp+2Ch], edi
		mov	edi, [eax+14h]
		mov	[ebp-14h], edi
		mov	edi, [eax+18h]
		mov	[ebp-1Ch], edi
		mov	edi, [eax+1Ch]
		mov	[ebp+30h], edi
		mov	edi, [eax+20h]
		mov	[ebp+34h], edi
		mov	edi, [ebp+6Ch]
		rol	edi, 7
		xor	edi, [ebp+18h]
		mov	[ebp+0], edi
		mov	edi, [ebp+68h]
		rol	edi, 7
		xor	edi, [ebp+24h]
		mov	[ebp-4], edi
		mov	edi, [ebp+64h]
		rol	edi, 7
		xor	edi, ecx
		mov	[ebp+10h], edi
		mov	edi, [ebp+70h]
		rol	edi, 7
		xor	edi, edx
		mov	[ebp+0Ch], edi
		mov	edi, [ebp+74h]
		rol	edi, 7
		xor	edi, [ebp+50h]
		mov	[ebp-24h], edi
		mov	edi, [ebp+60h]
		rol	edi, 7
		xor	edi, [ebp+48h]
		mov	[ebp+1Ch], edi
		mov	edi, [ebp+54h]
		rol	edi, 7
		xor	edi, esi
		mov	[ebp+8], edi
		mov	edi, [ebp+5Ch]
		rol	edi, 7
		xor	edi, [ebp+40h]
		mov	[ebp+4], edi
		mov	edi, [ebp+58h]
		rol	edi, 7
		xor	edi, [ebp+20h]
		mov	[ebp+6Ch], edi
		mov	edi, [ebp-10h]
		rol	edi, 7
		xor	edi, [ebp-0Ch]
		mov	[ebp+68h], edi
		mov	edi, [ebp-20h]
		rol	edi, 7
		xor	edi, [ebp+38h]
		mov	[ebp+64h], edi
		mov	edi, ebx
		mov	ebx, [ebp+18h]
		rol	edi, 7
		xor	edi, [ebp+14h]
		mov	[ebp+58h], ebx
		mov	ebx, [ebp+24h]
		mov	[ebp+70h], edi
		mov	edi, [ebp-14h]
		rol	edi, 7
		xor	edi, [ebp+4Ch]
		mov	[ebp-8], ebx
		mov	ebx, [ebp+50h]
		mov	[ebp+74h], edi
		mov	edi, [ebp-1Ch]
		rol	edi, 7
		xor	edi, [ebp+28h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+48h]
		mov	[ebp+60h], edi
		mov	edi, [ebp+30h]
		rol	edi, 7
		xor	edi, [ebp+3Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+20h]
		mov	[ebp-20h], ebx
		mov	ebx, [ebp-0Ch]
		mov	[ebp+54h], edi
		mov	edi, [ebp+34h]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+4Ch]
		rol	edi, 7
		xor	edi, [ebp+44h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+28h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+0]
		add	ecx, ebx
		mov	[ebp+18h], ecx
		mov	ecx, [ebp-4]
		add	edx, ecx
		mov	ecx, [ebp+58h]
		mov	ebx, [ebp+8]
		mov	[ebp+24h], edx
		mov	edx, [ebp+10h]
		add	ecx, edx
		mov	edx, [ebp+0Ch]
		mov	[ebp-10h], ecx
		mov	ecx, [ebp-8]
		add	ecx, edx
		mov	edx, [ebp+1Ch]
		mov	[ebp-8], ecx
		mov	ecx, [ebp-24h]
		add	esi, ecx
		mov	[ebp+50h], esi
		mov	esi, [ebp+40h]
		add	esi, edx
		mov	[ebp+48h], esi
		mov	esi, [ebp-18h]
		add	esi, ebx
		mov	ebx, [ebp+4]
		mov	[ebp+58h], esi
		mov	esi, [ebp+5Ch]
		add	esi, ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp+40h], esi
		mov	esi, [ebp+38h]
		add	esi, ebx
		mov	ebx, [ebp+68h]
		mov	[ebp+20h], esi
		mov	esi, [ebp+14h]
		add	esi, ebx
		mov	ebx, [ebp+64h]
		mov	[ebp-0Ch], esi
		mov	esi, [ebp-20h]
		add	esi, ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+38h], esi
		mov	esi, [ebp+2Ch]
		add	esi, ebx
		mov	ebx, [ebp+74h]
		mov	[ebp+14h], esi
		mov	esi, [ebp+3Ch]
		add	esi, ebx
		mov	ebx, [ebp+60h]
		mov	[ebp+4Ch], esi
		mov	esi, [ebp+44h]
		add	esi, ebx
		mov	ebx, [ebp+30h]
		mov	[ebp+28h], esi
		mov	esi, [ebp+54h]
		add	ebx, esi
		mov	[ebp+3Ch], ebx
		mov	ebx, [ebp+34h]
		add	ebx, edi
		mov	[ebp+44h], ebx
		mov	ebx, [ebp+0]
		mov	[ebp+1Ch], ebx
		mov	ebx, [ebp-4]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+10h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+0Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp-14h], ebx
		mov	ebx, [ebp+68h]
		mov	[ebp-1Ch], ebx
		mov	ebx, [ebp+64h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+18h]
		rol	ecx, 0Bh
		xor	ecx, ebx
		mov	[ebp+0], ecx
		mov	ecx, [ebp+8]
		rol	edx, 0Bh
		xor	edx, [ebp+24h]
		rol	ecx, 0Bh
		xor	ecx, [ebp-10h]
		mov	[ebp-4], edx
		mov	[ebp+10h], ecx
		mov	ecx, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp-8]
		mov	edx, [ebp-0Ch]
		mov	[ebp+0Ch], ecx
		mov	ecx, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+50h]
		mov	[ebp-24h], ecx
		mov	ecx, [ebp+2Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+48h]
		mov	[ebp+1Ch], ecx
		mov	ecx, [ebp-18h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+58h]
		mov	[ebp+8], ecx
		mov	ecx, [ebp+5Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+40h]
		mov	[ebp+4], ecx
		mov	ecx, [ebp+74h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+20h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [ebp+60h]
		rol	ecx, 0Bh
		xor	ecx, edx
		rol	esi, 0Bh
		xor	esi, [ebp+38h]
		rol	edi, 0Bh
		mov	[ebp+68h], ecx
		mov	ecx, [ebp-14h]
		mov	[ebp+64h], esi
		mov	esi, [ebp+14h]
		xor	edi, esi
		mov	[ebp+70h], edi
		mov	edi, [ebp+0]
		mov	[eax+4], edi
		mov	edi, [ebp-4]
		mov	[eax+8], edi
		mov	edi, [ebp+10h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+4Ch]
		mov	[eax+0Ch], edi
		mov	edi, [ebp+0Ch]
		mov	[ebp+74h], ecx
		mov	ecx, [ebp-1Ch]
		mov	[eax+10h], edi
		mov	edi, [ebp-24h]
		mov	[eax+14h], edi
		mov	edi, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+28h]
		mov	[eax+18h], edi
		mov	edi, [ebp+8]
		mov	[ebp+60h], ecx
		mov	ecx, [ebp+30h]
		mov	[eax+1Ch], edi
		mov	edi, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp+3Ch]
		mov	[eax+20h], edi
		mov	edi, [ebp+6Ch]
		mov	[eax+24h], edi
		mov	edi, [ebp+68h]
		mov	[ebp+54h], ecx
		mov	ecx, [ebp+34h]
		mov	[eax+28h], edi
		mov	edi, [ebp+64h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+44h]
		mov	[eax+2Ch], edi
		mov	edi, [ebp+70h]
		mov	[eax+40h], ecx
		mov	ecx, [ebp+24h]
		mov	[eax+44h], ecx
		mov	ecx, [ebp-8]
		mov	[eax+4Ch], ecx
		mov	ecx, [ebp-10h]
		mov	[eax+50h], ecx
		mov	ecx, [ebp+48h]
		mov	[eax+54h], ecx
		mov	ecx, [ebp+50h]
		mov	[eax+58h], ecx
		mov	ecx, [ebp+40h]
		mov	[eax+5Ch], ecx
		mov	ecx, [ebp+58h]
		mov	[eax+60h], ecx
		mov	ecx, [ebp+20h]
		mov	[eax+68h], ecx
		mov	ecx, [ebp+38h]
		mov	[eax+70h], ecx
		mov	ecx, [ebp+28h]
		mov	[eax+30h], edi
		mov	edi, [ebp+74h]
		mov	[eax+74h], ecx
		mov	ecx, [ebp+4Ch]
		mov	[eax+34h], edi
		mov	edi, [ebp+60h]
		mov	[eax+78h], ecx
		mov	ecx, [ebp+44h]
		mov	[eax+38h], edi
		mov	edi, [ebp+54h]
		mov	[eax+7Ch], ecx
		mov	ecx, [ebp+3Ch]
		mov	[eax+3Ch], edi
		mov	[eax+48h], ebx
		mov	[eax+64h], edx
		mov	[eax+6Ch], esi
		mov	[eax+80h], ecx
		call	sub_406AEC
		pop	edi
		pop	esi
		pop	ebx
		add	ebp, 78h
		leave
		retn

sub_405D42:		; CODE XREF: hash_mix_buf+42Ap


		push	ebp
		lea	ebp, [esp-78h]
		sub	esp, 9Ch
		mov	ecx, [eax+24h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [eax+28h]
		mov	edx, [eax+4]
		mov	[ebp+68h], ecx
		mov	ecx, [eax+2Ch]
		mov	[ebp+64h], ecx
		mov	ecx, [eax+30h]
		mov	[ebp+70h], ecx
		mov	ecx, [eax+34h]
		mov	[ebp+74h], ecx
		mov	ecx, [eax+38h]
		mov	[ebp+60h], ecx
		mov	ecx, [eax+3Ch]
		mov	[ebp+54h], ecx
		mov	ecx, [eax+40h]
		mov	[ebp+5Ch], ecx
		mov	ecx, [eax+44h]
		add	ecx, edx
		push	ebx
		push	esi
		mov	esi, [eax+8]
		push	edi
		mov	edi, [eax+0Ch]
		mov	[ebp+18h], ecx
		mov	ecx, [eax+48h]
		add	ecx, esi
		mov	[ebp+24h], ecx
		mov	ecx, [eax+4Ch]
		add	ecx, edi
		mov	edi, [eax+60h]
		add	edi, [eax+20h]
		mov	esi, [eax+54h]
		mov	[ebp+40h], edi
		mov	edi, [eax+64h]
		add	edi, [ebp+6Ch]
		add	esi, [eax+14h]
		mov	[ebp+20h], edi
		mov	edi, [eax+68h]
		add	edi, [ebp+68h]
		mov	ebx, [eax+10h]
		mov	[ebp-0Ch], edi
		mov	edi, [eax+6Ch]
		add	edi, [ebp+64h]
		mov	edx, [eax+50h]
		mov	[ebp+38h], edi
		mov	edi, [eax+70h]
		add	edi, [ebp+70h]
		mov	[ebp+50h], esi
		mov	esi, [eax+58h]
		add	esi, [eax+18h]
		mov	[ebp+14h], edi
		mov	edi, [eax+74h]
		add	edi, [ebp+74h]
		mov	[ebp+48h], esi
		mov	esi, [eax+5Ch]
		add	esi, [eax+1Ch]
		mov	[ebp+4Ch], edi
		mov	edi, [eax+78h]
		add	edi, [ebp+60h]
		add	edx, ebx
		mov	[ebp+28h], edi
		mov	edi, [eax+7Ch]
		add	edi, [ebp+54h]
		mov	[ebp+3Ch], edi
		mov	edi, [eax+80h]
		add	edi, [ebp+5Ch]
		mov	[ebp+44h], edi
		mov	edi, [eax+4]
		mov	[ebp+58h], edi
		mov	edi, [eax+8]
		mov	[ebp-10h], edi
		mov	edi, [eax+0Ch]
		mov	[ebp-20h], edi
		mov	edi, ebx
		mov	[ebp+2Ch], edi
		mov	edi, [eax+14h]
		mov	[ebp-14h], edi
		mov	edi, [eax+18h]
		mov	[ebp-1Ch], edi
		mov	edi, [eax+1Ch]
		mov	[ebp+30h], edi
		mov	edi, [eax+20h]
		mov	[ebp+34h], edi
		mov	edi, [ebp+6Ch]
		rol	edi, 7
		xor	edi, [ebp+18h]
		mov	[ebp+0], edi
		mov	edi, [ebp+68h]
		rol	edi, 7
		xor	edi, [ebp+24h]
		mov	[ebp-4], edi
		mov	edi, [ebp+64h]
		rol	edi, 7
		xor	edi, ecx
		mov	[ebp+10h], edi
		mov	edi, [ebp+70h]
		rol	edi, 7
		xor	edi, edx
		mov	[ebp+0Ch], edi
		mov	edi, [ebp+74h]
		rol	edi, 7
		xor	edi, [ebp+50h]
		mov	[ebp-24h], edi
		mov	edi, [ebp+60h]
		rol	edi, 7
		xor	edi, [ebp+48h]
		mov	[ebp+1Ch], edi
		mov	edi, [ebp+54h]
		rol	edi, 7
		xor	edi, esi
		mov	[ebp+8], edi
		mov	edi, [ebp+5Ch]
		rol	edi, 7
		xor	edi, [ebp+40h]
		mov	[ebp+4], edi
		mov	edi, [ebp+58h]
		rol	edi, 7
		xor	edi, [ebp+20h]
		mov	[ebp+6Ch], edi
		mov	edi, [ebp-10h]
		rol	edi, 7
		xor	edi, [ebp-0Ch]
		mov	[ebp+68h], edi
		mov	edi, [ebp-20h]
		rol	edi, 7
		xor	edi, [ebp+38h]
		mov	[ebp+64h], edi
		mov	edi, ebx
		mov	ebx, [ebp+18h]
		rol	edi, 7
		xor	edi, [ebp+14h]
		mov	[ebp+58h], ebx
		mov	ebx, [ebp+24h]
		mov	[ebp+70h], edi
		mov	edi, [ebp-14h]
		rol	edi, 7
		xor	edi, [ebp+4Ch]
		mov	[ebp-8], ebx
		mov	ebx, [ebp+50h]
		mov	[ebp+74h], edi
		mov	edi, [ebp-1Ch]
		rol	edi, 7
		xor	edi, [ebp+28h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+48h]
		mov	[ebp+60h], edi
		mov	edi, [ebp+30h]
		rol	edi, 7
		xor	edi, [ebp+3Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+20h]
		mov	[ebp-20h], ebx
		mov	ebx, [ebp-0Ch]
		mov	[ebp+54h], edi
		mov	edi, [ebp+34h]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+4Ch]
		rol	edi, 7
		xor	edi, [ebp+44h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+28h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+0]
		add	ecx, ebx
		mov	[ebp+18h], ecx
		mov	ecx, [ebp-4]
		add	edx, ecx
		mov	ecx, [ebp+58h]
		mov	ebx, [ebp+8]
		mov	[ebp+24h], edx
		mov	edx, [ebp+10h]
		add	ecx, edx
		mov	edx, [ebp+0Ch]
		mov	[ebp-10h], ecx
		mov	ecx, [ebp-8]
		add	ecx, edx
		mov	edx, [ebp+1Ch]
		mov	[ebp-8], ecx
		mov	ecx, [ebp-24h]
		add	esi, ecx
		mov	[ebp+50h], esi
		mov	esi, [ebp+40h]
		add	esi, edx
		mov	[ebp+48h], esi
		mov	esi, [ebp-18h]
		add	esi, ebx
		mov	ebx, [ebp+4]
		mov	[ebp+58h], esi
		mov	esi, [ebp+5Ch]
		add	esi, ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp+40h], esi
		mov	esi, [ebp+38h]
		add	esi, ebx
		mov	ebx, [ebp+68h]
		mov	[ebp+20h], esi
		mov	esi, [ebp+14h]
		add	esi, ebx
		mov	ebx, [ebp+64h]
		mov	[ebp-0Ch], esi
		mov	esi, [ebp-20h]
		add	esi, ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+38h], esi
		mov	esi, [ebp+2Ch]
		add	esi, ebx
		mov	ebx, [ebp+74h]
		mov	[ebp+14h], esi
		mov	esi, [ebp+3Ch]
		add	esi, ebx
		mov	ebx, [ebp+60h]
		mov	[ebp+4Ch], esi
		mov	esi, [ebp+44h]
		add	esi, ebx
		mov	ebx, [ebp+30h]
		mov	[ebp+28h], esi
		mov	esi, [ebp+54h]
		add	ebx, esi
		mov	[ebp+3Ch], ebx
		mov	ebx, [ebp+34h]
		add	ebx, edi
		mov	[ebp+44h], ebx
		mov	ebx, [ebp+0]
		mov	[ebp+1Ch], ebx
		mov	ebx, [ebp-4]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+10h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+0Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp-14h], ebx
		mov	ebx, [ebp+68h]
		mov	[ebp-1Ch], ebx
		mov	ebx, [ebp+64h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+18h]
		rol	ecx, 0Bh
		xor	ecx, ebx
		mov	[ebp+0], ecx
		mov	ecx, [ebp+8]
		rol	edx, 0Bh
		xor	edx, [ebp+24h]
		rol	ecx, 0Bh
		xor	ecx, [ebp-10h]
		mov	[ebp-4], edx
		mov	[ebp+10h], ecx
		mov	ecx, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp-8]
		mov	edx, [ebp-0Ch]
		mov	[ebp+0Ch], ecx
		mov	ecx, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+50h]
		mov	[ebp-24h], ecx
		mov	ecx, [ebp+2Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+48h]
		mov	[ebp+1Ch], ecx
		mov	ecx, [ebp-18h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+58h]
		mov	[ebp+8], ecx
		mov	ecx, [ebp+5Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+40h]
		mov	[ebp+4], ecx
		mov	ecx, [ebp+74h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+20h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [ebp+60h]
		rol	ecx, 0Bh
		xor	ecx, edx
		rol	esi, 0Bh
		xor	esi, [ebp+38h]
		rol	edi, 0Bh
		mov	[ebp+68h], ecx
		mov	ecx, [ebp-14h]
		mov	[ebp+64h], esi
		mov	esi, [ebp+14h]
		xor	edi, esi
		mov	[ebp+70h], edi
		mov	edi, [ebp+0]
		mov	[eax+4], edi
		mov	edi, [ebp-4]
		mov	[eax+8], edi
		mov	edi, [ebp+10h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+4Ch]
		mov	[eax+0Ch], edi
		mov	edi, [ebp+0Ch]
		mov	[ebp+74h], ecx
		mov	ecx, [ebp-1Ch]
		mov	[eax+10h], edi
		mov	edi, [ebp-24h]
		mov	[eax+14h], edi
		mov	edi, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+28h]
		mov	[eax+18h], edi
		mov	edi, [ebp+8]
		mov	[ebp+60h], ecx
		mov	ecx, [ebp+30h]
		mov	[eax+1Ch], edi
		mov	edi, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp+3Ch]
		mov	[eax+20h], edi
		mov	edi, [ebp+6Ch]
		mov	[eax+24h], edi
		mov	edi, [ebp+68h]
		mov	[ebp+54h], ecx
		mov	ecx, [ebp+34h]
		mov	[eax+28h], edi
		mov	edi, [ebp+64h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+44h]
		mov	[eax+2Ch], edi
		mov	edi, [ebp+70h]
		mov	[eax+40h], ecx
		mov	ecx, [ebp+24h]
		mov	[eax+44h], ecx
		mov	ecx, [ebp-8]
		mov	[eax+4Ch], ecx
		mov	ecx, [ebp-10h]
		mov	[eax+50h], ecx
		mov	ecx, [ebp+48h]
		mov	[eax+54h], ecx
		mov	ecx, [ebp+50h]
		mov	[eax+58h], ecx
		mov	ecx, [ebp+40h]
		mov	[eax+5Ch], ecx
		mov	ecx, [ebp+58h]
		mov	[eax+60h], ecx
		mov	ecx, [ebp+20h]
		mov	[eax+68h], ecx
		mov	ecx, [ebp+38h]
		mov	[eax+70h], ecx
		mov	ecx, [ebp+28h]
		mov	[eax+30h], edi
		mov	edi, [ebp+74h]
		mov	[eax+74h], ecx
		mov	ecx, [ebp+4Ch]
		mov	[eax+34h], edi
		mov	edi, [ebp+60h]
		mov	[eax+78h], ecx
		mov	ecx, [ebp+44h]
		mov	[eax+38h], edi
		mov	edi, [ebp+54h]
		mov	[eax+7Ch], ecx
		mov	ecx, [ebp+3Ch]
		mov	[eax+3Ch], edi
		mov	[eax+48h], ebx
		mov	[eax+64h], edx
		mov	[eax+6Ch], esi
		mov	[eax+80h], ecx
		call	sub_406605
		pop	edi
		pop	esi
		pop	ebx
		add	ebp, 78h
		leave
		retn


hash_mix_buf:
		push	ebp
		lea	ebp, [esp-78h]
		sub	esp, 9Ch
		mov	ecx, [eax+24h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [eax+28h]
		mov	edx, [eax+4]
		mov	[ebp+68h], ecx
		mov	ecx, [eax+2Ch]
		mov	[ebp+64h], ecx
		mov	ecx, [eax+30h]
		mov	[ebp+70h], ecx
		mov	ecx, [eax+34h]
		mov	[ebp+74h], ecx
		mov	ecx, [eax+38h]
		mov	[ebp+60h], ecx
		mov	ecx, [eax+3Ch]
		mov	[ebp+54h], ecx
		mov	ecx, [eax+40h]
		mov	[ebp+5Ch], ecx
		mov	ecx, [eax+44h]
		add	ecx, edx
		push	ebx
		push	esi
		mov	esi, [eax+8]
		push	edi
		mov	edi, [eax+0Ch]
		mov	[ebp+18h], ecx
		mov	ecx, [eax+48h]
		add	ecx, esi
		mov	[ebp+24h], ecx
		mov	ecx, [eax+4Ch]
		add	ecx, edi
		mov	edi, [eax+60h]
		add	edi, [eax+20h]
		mov	esi, [eax+54h]
		mov	[ebp+40h], edi
		mov	edi, [eax+64h]
		add	edi, [ebp+6Ch]
		add	esi, [eax+14h]
		mov	[ebp+20h], edi
		mov	edi, [eax+68h]
		add	edi, [ebp+68h]
		mov	ebx, [eax+10h]
		mov	[ebp-0Ch], edi
		mov	edi, [eax+6Ch]
		add	edi, [ebp+64h]
		mov	edx, [eax+50h]
		mov	[ebp+38h], edi
		mov	edi, [eax+70h]
		add	edi, [ebp+70h]
		mov	[ebp+50h], esi
		mov	esi, [eax+58h]
		add	esi, [eax+18h]
		mov	[ebp+14h], edi
		mov	edi, [eax+74h]
		add	edi, [ebp+74h]
		mov	[ebp+48h], esi
		mov	esi, [eax+5Ch]
		add	esi, [eax+1Ch]
		mov	[ebp+4Ch], edi
		mov	edi, [eax+78h]
		add	edi, [ebp+60h]
		add	edx, ebx
		mov	[ebp+28h], edi
		mov	edi, [eax+7Ch]
		add	edi, [ebp+54h]
		mov	[ebp+3Ch], edi
		mov	edi, [eax+80h]
		add	edi, [ebp+5Ch]
		mov	[ebp+44h], edi
		mov	edi, [eax+4]
		mov	[ebp+58h], edi
		mov	edi, [eax+8]
		mov	[ebp-10h], edi
		mov	edi, [eax+0Ch]
		mov	[ebp-20h], edi
		mov	edi, ebx
		mov	[ebp+2Ch], edi
		mov	edi, [eax+14h]
		mov	[ebp-14h], edi
		mov	edi, [eax+18h]
		mov	[ebp-1Ch], edi
		mov	edi, [eax+1Ch]
		mov	[ebp+30h], edi
		mov	edi, [eax+20h]
		mov	[ebp+34h], edi
		mov	edi, [ebp+6Ch]
		rol	edi, 7
		xor	edi, [ebp+18h]
		mov	[ebp+0], edi
		mov	edi, [ebp+68h]
		rol	edi, 7
		xor	edi, [ebp+24h]
		mov	[ebp-4], edi
		mov	edi, [ebp+64h]
		rol	edi, 7
		xor	edi, ecx
		mov	[ebp+10h], edi
		mov	edi, [ebp+70h]
		rol	edi, 7
		xor	edi, edx
		mov	[ebp+0Ch], edi
		mov	edi, [ebp+74h]
		rol	edi, 7
		xor	edi, [ebp+50h]
		mov	[ebp-24h], edi
		mov	edi, [ebp+60h]
		rol	edi, 7
		xor	edi, [ebp+48h]
		mov	[ebp+1Ch], edi
		mov	edi, [ebp+54h]
		rol	edi, 7
		xor	edi, esi
		mov	[ebp+8], edi
		mov	edi, [ebp+5Ch]
		rol	edi, 7
		xor	edi, [ebp+40h]
		mov	[ebp+4], edi
		mov	edi, [ebp+58h]
		rol	edi, 7
		xor	edi, [ebp+20h]
		mov	[ebp+6Ch], edi
		mov	edi, [ebp-10h]
		rol	edi, 7
		xor	edi, [ebp-0Ch]
		mov	[ebp+68h], edi
		mov	edi, [ebp-20h]
		rol	edi, 7
		xor	edi, [ebp+38h]
		mov	[ebp+64h], edi
		mov	edi, ebx
		mov	ebx, [ebp+18h]
		rol	edi, 7
		xor	edi, [ebp+14h]
		mov	[ebp+58h], ebx
		mov	ebx, [ebp+24h]
		mov	[ebp+70h], edi
		mov	edi, [ebp-14h]
		rol	edi, 7
		xor	edi, [ebp+4Ch]
		mov	[ebp-8], ebx
		mov	ebx, [ebp+50h]
		mov	[ebp+74h], edi
		mov	edi, [ebp-1Ch]
		rol	edi, 7
		xor	edi, [ebp+28h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+48h]
		mov	[ebp+60h], edi
		mov	edi, [ebp+30h]
		rol	edi, 7
		xor	edi, [ebp+3Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+20h]
		mov	[ebp-20h], ebx
		mov	ebx, [ebp-0Ch]
		mov	[ebp+54h], edi
		mov	edi, [ebp+34h]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+4Ch]
		rol	edi, 7
		xor	edi, [ebp+44h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+28h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+0]
		add	ecx, ebx
		mov	[ebp+18h], ecx
		mov	ecx, [ebp-4]
		add	edx, ecx
		mov	ecx, [ebp+58h]
		mov	ebx, [ebp+8]
		mov	[ebp+24h], edx
		mov	edx, [ebp+10h]
		add	ecx, edx
		mov	edx, [ebp+0Ch]
		mov	[ebp-10h], ecx
		mov	ecx, [ebp-8]
		add	ecx, edx
		mov	edx, [ebp+1Ch]
		mov	[ebp-8], ecx
		mov	ecx, [ebp-24h]
		add	esi, ecx
		mov	[ebp+50h], esi
		mov	esi, [ebp+40h]
		add	esi, edx
		mov	[ebp+48h], esi
		mov	esi, [ebp-18h]
		add	esi, ebx
		mov	ebx, [ebp+4]
		mov	[ebp+58h], esi
		mov	esi, [ebp+5Ch]
		add	esi, ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp+40h], esi
		mov	esi, [ebp+38h]
		add	esi, ebx
		mov	ebx, [ebp+68h]
		mov	[ebp+20h], esi
		mov	esi, [ebp+14h]
		add	esi, ebx
		mov	ebx, [ebp+64h]
		mov	[ebp-0Ch], esi
		mov	esi, [ebp-20h]
		add	esi, ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+38h], esi
		mov	esi, [ebp+2Ch]
		add	esi, ebx
		mov	ebx, [ebp+74h]
		mov	[ebp+14h], esi
		mov	esi, [ebp+3Ch]
		add	esi, ebx
		mov	ebx, [ebp+60h]
		mov	[ebp+4Ch], esi
		mov	esi, [ebp+44h]
		add	esi, ebx
		mov	ebx, [ebp+30h]
		mov	[ebp+28h], esi
		mov	esi, [ebp+54h]
		add	ebx, esi
		mov	[ebp+3Ch], ebx
		mov	ebx, [ebp+34h]
		add	ebx, edi
		mov	[ebp+44h], ebx
		mov	ebx, [ebp+0]
		mov	[ebp+1Ch], ebx
		mov	ebx, [ebp-4]
		mov	[ebp+2Ch], ebx
		mov	ebx, [ebp+10h]
		mov	[ebp-18h], ebx
		mov	ebx, [ebp+0Ch]
		mov	[ebp+5Ch], ebx
		mov	ebx, [ebp+6Ch]
		mov	[ebp-14h], ebx
		mov	ebx, [ebp+68h]
		mov	[ebp-1Ch], ebx
		mov	ebx, [ebp+64h]
		mov	[ebp+30h], ebx
		mov	ebx, [ebp+70h]
		mov	[ebp+34h], ebx
		mov	ebx, [ebp+18h]
		rol	ecx, 0Bh
		xor	ecx, ebx
		mov	[ebp+0], ecx
		mov	ecx, [ebp+8]
		rol	edx, 0Bh
		xor	edx, [ebp+24h]
		rol	ecx, 0Bh
		xor	ecx, [ebp-10h]
		mov	[ebp-4], edx
		mov	[ebp+10h], ecx
		mov	ecx, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp-8]
		mov	edx, [ebp-0Ch]
		mov	[ebp+0Ch], ecx
		mov	ecx, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+50h]
		mov	[ebp-24h], ecx
		mov	ecx, [ebp+2Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+48h]
		mov	[ebp+1Ch], ecx
		mov	ecx, [ebp-18h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+58h]
		mov	[ebp+8], ecx
		mov	ecx, [ebp+5Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+40h]
		mov	[ebp+4], ecx
		mov	ecx, [ebp+74h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+20h]
		mov	[ebp+6Ch], ecx
		mov	ecx, [ebp+60h]
		rol	ecx, 0Bh
		xor	ecx, edx
		rol	esi, 0Bh
		xor	esi, [ebp+38h]
		rol	edi, 0Bh
		mov	[ebp+68h], ecx
		mov	ecx, [ebp-14h]
		mov	[ebp+64h], esi
		mov	esi, [ebp+14h]
		xor	edi, esi
		mov	[ebp+70h], edi
		mov	edi, [ebp+0]
		mov	[eax+4], edi
		mov	edi, [ebp-4]
		mov	[eax+8], edi
		mov	edi, [ebp+10h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+4Ch]
		mov	[eax+0Ch], edi
		mov	edi, [ebp+0Ch]
		mov	[ebp+74h], ecx
		mov	ecx, [ebp-1Ch]
		mov	[eax+10h], edi
		mov	edi, [ebp-24h]
		mov	[eax+14h], edi
		mov	edi, [ebp+1Ch]
		rol	ecx, 0Bh
		xor	ecx, [ebp+28h]
		mov	[eax+18h], edi
		mov	edi, [ebp+8]
		mov	[ebp+60h], ecx
		mov	ecx, [ebp+30h]
		mov	[eax+1Ch], edi
		mov	edi, [ebp+4]
		rol	ecx, 0Bh
		xor	ecx, [ebp+3Ch]
		mov	[eax+20h], edi
		mov	edi, [ebp+6Ch]
		mov	[eax+24h], edi
		mov	edi, [ebp+68h]
		mov	[ebp+54h], ecx
		mov	ecx, [ebp+34h]
		mov	[eax+28h], edi
		mov	edi, [ebp+64h]
		rol	ecx, 0Bh
		xor	ecx, [ebp+44h]
		mov	[eax+2Ch], edi
		mov	edi, [ebp+70h]
		mov	[eax+40h], ecx
		mov	ecx, [ebp+24h]
		mov	[eax+44h], ecx
		mov	ecx, [ebp-8]
		mov	[eax+4Ch], ecx
		mov	ecx, [ebp-10h]
		mov	[eax+50h], ecx
		mov	ecx, [ebp+48h]
		mov	[eax+54h], ecx
		mov	ecx, [ebp+50h]
		mov	[eax+58h], ecx
		mov	ecx, [ebp+40h]
		mov	[eax+5Ch], ecx
		mov	ecx, [ebp+58h]
		mov	[eax+60h], ecx
		mov	ecx, [ebp+20h]
		mov	[eax+68h], ecx
		mov	ecx, [ebp+38h]
		mov	[eax+70h], ecx
		mov	ecx, [ebp+28h]
		mov	[eax+30h], edi
		mov	edi, [ebp+74h]
		mov	[eax+74h], ecx
		mov	ecx, [ebp+4Ch]
		mov	[eax+34h], edi
		mov	edi, [ebp+60h]
		mov	[eax+78h], ecx
		mov	ecx, [ebp+44h]
		mov	[eax+38h], edi
		mov	edi, [ebp+54h]
		mov	[eax+7Ch], ecx
		mov	ecx, [ebp+3Ch]
		mov	[eax+3Ch], edi
		mov	[eax+48h], ebx
		mov	[eax+64h], edx
		mov	[eax+6Ch], esi
		mov	[eax+80h], ecx
		call	sub_405D42
		pop	edi
		pop	esi
		pop	ebx
		add	ebp, 78h
		leave
		retn

hash_mix:
    mov eax, [esp+4]
    call hash_mix_buf
    ret 

